package com.dev.bayan.ibrahim.feature.quiz_builder.ui.theme

import androidx.compose.ui.graphics.Color

val quiz_builder_light_primary = Color(0xFF4758A9)
val quiz_builder_light_onPrimary = Color(0xFFFFFFFF)
val quiz_builder_light_primaryContainer = Color(0xFFDDE1FF)
val quiz_builder_light_onPrimaryContainer = Color(0xFF001257)
val quiz_builder_light_secondary = Color(0xFF626200)
val quiz_builder_light_onSecondary = Color(0xFFFFFFFF)
val quiz_builder_light_secondaryContainer = Color(0xFFE9E95B)
val quiz_builder_light_onSecondaryContainer = Color(0xFF1D1D00)
val quiz_builder_light_tertiary = Color(0xFF76546E)
val quiz_builder_light_onTertiary = Color(0xFFFFFFFF)
val quiz_builder_light_tertiaryContainer = Color(0xFFFFD7F3)
val quiz_builder_light_onTertiaryContainer = Color(0xFF2D1228)
val quiz_builder_light_error = Color(0xFFBA1A1A)
val quiz_builder_light_onError = Color(0xFFFFFFFF)
val quiz_builder_light_errorContainer = Color(0xFFFFDAD6)
val quiz_builder_light_onErrorContainer = Color(0xFF410002)
val quiz_builder_light_outline = Color(0xFF767680)
val quiz_builder_light_background = Color(0xFFFEFBFF)
val quiz_builder_light_onBackground = Color(0xFF1B1B1F)
val quiz_builder_light_surface = Color(0xFFFBF8FD)
val quiz_builder_light_onSurface = Color(0xFF1B1B1F)
val quiz_builder_light_surfaceVariant = Color(0xFFE3E1EC)
val quiz_builder_light_onSurfaceVariant = Color(0xFF45464F)
val quiz_builder_light_inverseSurface = Color(0xFF303034)
val quiz_builder_light_inverseOnSurface = Color(0xFFF3F0F4)
val quiz_builder_light_inversePrimary = Color(0xFFB9C3FF)
val quiz_builder_light_surfaceTint = Color(0xFF4758A9)
val quiz_builder_light_outlineVariant = Color(0xFFC6C5D0)
val quiz_builder_light_scrim = Color(0xFF000000)

val quiz_builder_dark_primary = Color(0xFFB9C3FF)
val quiz_builder_dark_onPrimary = Color(0xFF132878)
val quiz_builder_dark_primaryContainer = Color(0xFF2E4090)
val quiz_builder_dark_onPrimaryContainer = Color(0xFFDDE1FF)
val quiz_builder_dark_secondary = Color(0xFFCDCC41)
val quiz_builder_dark_onSecondary = Color(0xFF323200)
val quiz_builder_dark_secondaryContainer = Color(0xFF494900)
val quiz_builder_dark_onSecondaryContainer = Color(0xFFE9E95B)
val quiz_builder_dark_tertiary = Color(0xFFE5BAD8)
val quiz_builder_dark_onTertiary = Color(0xFF44263E)
val quiz_builder_dark_tertiaryContainer = Color(0xFF5C3C55)
val quiz_builder_dark_onTertiaryContainer = Color(0xFFFFD7F3)
val quiz_builder_dark_error = Color(0xFFFFB4AB)
val quiz_builder_dark_onError = Color(0xFF690005)
val quiz_builder_dark_errorContainer = Color(0xFF93000A)
val quiz_builder_dark_onErrorContainer = Color(0xFFFFDAD6)
val quiz_builder_dark_outline = Color(0xFF90909A)
val quiz_builder_dark_background = Color(0xFF1B1B1F)
val quiz_builder_dark_onBackground = Color(0xFFE4E1E6)
val quiz_builder_dark_surface = Color(0xFF131316)
val quiz_builder_dark_onSurface = Color(0xFFC8C6CA)
val quiz_builder_dark_surfaceVariant = Color(0xFF45464F)
val quiz_builder_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val quiz_builder_dark_inverseSurface = Color(0xFFE4E1E6)
val quiz_builder_dark_inverseOnSurface = Color(0xFF1B1B1F)
val quiz_builder_dark_inversePrimary = Color(0xFF4758A9)
val quiz_builder_dark_surfaceTint = Color(0xFFB9C3FF)
val quiz_builder_dark_outlineVariant = Color(0xFF45464F)
val quiz_builder_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF2E3867)
